In [120]:
import os
import pandas as pd

In [121]:
call = pd.read_csv('Call.csv', encoding='cp949')
interestdiff = pd.read_csv('InterestDiff.csv', encoding='cp949')
vkospi = pd.read_csv('VKOSPI.csv', encoding='cp949')
tradbal = pd.read_excel('TradeBalance.xlsx')
cpi = pd.read_excel('CPI.xlsx')
ppi = pd.read_csv('PPI.csv', encoding='cp949')
unemploy = pd.read_excel('Unemployment.xlsx')
manuprod = pd.read_excel('ManufactProduct.xlsx')
spread = pd.read_csv('SPREAD.csv', encoding='cp949')
erlog = pd.read_csv('Erlog.csv', encoding='cp949')

In [122]:
spread.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1234 entries, 0 to 1233
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   시점      1234 non-null   object
 1   SPREAD  1234 non-null   float64
dtypes: float64(1), object(1)
memory usage: 19.4+ KB

In [123]:
# datetime 변환
call['시점'] = pd.to_datetime(call['시점'])
interestdiff['시점'] = pd.to_datetime(interestdiff['시점'])
vkospi['시점'] = pd.to_datetime(vkospi['시점'])
tradbal['시점'] = pd.to_datetime(tradbal['시점'])
cpi['시점'] = pd.to_datetime(cpi['시점'])
ppi['시점'] = pd.to_datetime(ppi['시점'])
unemploy['시점'] = pd.to_datetime(unemploy['시점'])
manuprod['시점'] = pd.to_datetime(manuprod['시점'])
spread['시점'] = pd.to_datetime(spread['시점'])
erlog['시점'] = pd.to_datetime(erlog['시점'])

In [124]:
# datetime 변환 확인
call.info()
interestdiff.info()
vkospi.info()
tradbal.info()
cpi.info()
ppi.info()
unemploy.info()
manuprod.info()
spread.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6358 entries, 0 to 6357
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   시점      6358 non-null   datetime64[ns]
 1   Call    6358 non-null   float64
dtypes: datetime64[ns](1), float64(1)
memory usage: 99.5 KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6613 entries, 0 to 6612
Data columns (total 2 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   시점            6613 non-null   datetime64[ns]
 1   InterestDiff  6343 non-null   float64
dtypes: datetime64[ns](1), float64(1)
memory usage: 103.5 KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2276 entries, 0 to 2275
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   시점      2276 non-null   datetime64[ns]
 1   VKOSPI  2276 non-null   float64
dtypes: datetime64[ns](1), float64(1)
memory usage: 35.7 KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 273 entries, 0 to 272
Data columns (total 2 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   시점            273 non-null    datetime64[ns]
 1   TradeBalance  273 non-null    int64
dtypes: datetime64[ns](1), int64(1)
memory usage: 4.4 KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 304 entries, 0 to 303
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   시점      304 non-null    datetime64[ns]
 1   CPI     304 non-null    float64
dtypes: datetime64[ns](1), float64(1)
memory usage: 4.9 KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   시점      303 non-null    datetime64[ns]
 1   PPI     303 non-null    float64
dtypes: datetime64[ns](1), float64(1)
memory usage: 4.9 KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 281 entries, 0 to 280
Data columns (total 2 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   시점            281 non-null    datetime64[ns]
 1   Unemployment  281 non-null    float64
dtypes: datetime64[ns](1), float64(1)
memory usage: 4.5 KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 2 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   시점               303 non-null    datetime64[ns]
 1   ManufactProduct  303 non-null    float64
dtypes: datetime64[ns](1), float64(1)
memory usage: 4.9 KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1234 entries, 0 to 1233
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   시점      1234 non-null   datetime64[ns]
 1   SPREAD  1234 non-null   float64
dtypes: datetime64[ns](1), float64(1)
memory usage: 19.4 KB

## 병합

### 1. VKOSPI 포함

In [125]:
# 병합
a = pd.merge(call, interestdiff, how='outer')
a = pd.merge(a, vkospi, how='outer')
a = pd.merge(a, tradbal, how='outer')
a = pd.merge(a, cpi, how='outer')
a = pd.merge(a, ppi, how='outer')
a = pd.merge(a, unemploy, how='outer')
a = pd.merge(a, manuprod, how='outer')
a = pd.merge(a, spread, how='outer')
a = pd.merge(a, erlog, how='outer')
a

,시점,Call,InterestDiff,VKOSPI,TradeBalance,CPI,PPI,Unemployment,ManufactProduct,SPREAD,Erlog
0,1997-07-07,11.23,0.35,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.790097
1,1997-07-08,11.16,0.35,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.791221
2,1997-07-09,10.95,0.35,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.791221
3,1997-07-10,10.95,0.35,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.792344
4,1997-07-11,11.07,0.34,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.793466
5,1997-07-12,11.07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,1997-07-14,11.20,0.32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.795146
7,1997-07-15,11.37,0.34,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.795706
8,1997-07-16,11.50,0.33,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.797940
9,1997-07-18,11.43,0.33,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.799056
10,1997-07-19,11.43,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,1997-07-21,11.41,0.33,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.796265
12,1997-07-22,11.38,0.25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.798498
13,1997-07-23,11.59,0.29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.798498
14,1997-07-24,11.60,0.29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.796824
...,...,...,...,...,...,...,...,...,...,...,...
6759,2020-03-01,NaN,NaN,NaN,4363344.0,99.940,102.82,4.2,113.600,-143438.48,NaN
6760,2020-08-01,NaN,NaN,NaN,3651302.0,100.190,103.22,3.1,99.700,0.80,NaN
6761,2020-11-01,NaN,NaN,NaN,5807120.0,100.090,103.09,3.4,111.800,-999.14,NaN
6762,2021-05-01,NaN,NaN,NaN,2814640.0,102.050,108.65,4.0,111.500,0.82,NaN
6763,2021-08-01,NaN,NaN,NaN,1584011.0,102.750,110.86,2.6,110.500,1.02,NaN
6764,2022-01-01,NaN,NaN,NaN,-4940394.0,104.690,114.40,4.1,115.100,1.58,NaN
6765,2022-05-01,NaN,NaN,NaN,-1605818.0,107.560,119.43,3.0,119.900,1.88,NaN
6766,1997-07-01,NaN,NaN,NaN,NaN,56.825,69.44,NaN,36.206,NaN,NaN
6767,1998-02-01,NaN,NaN,NaN,NaN,61.453,79.72,NaN,32.509,NaN,NaN
6768,1998-03-01,NaN,NaN,NaN,NaN,61.349,79.55,NaN,33.999,NaN,NaN
6769,1998-08-01,NaN,NaN,NaN,NaN,61.192,77.73,NaN,30.976,NaN,NaN
6770,1998-11-01,NaN,NaN,NaN,NaN,61.453,77.69,NaN,37.791,NaN,NaN
6771,1999-05-01,NaN,NaN,NaN,NaN,61.712,76.64,NaN,41.044,NaN,NaN
6772,1999-08-01,NaN,NaN,NaN,NaN,61.765,76.52,6.2,40.893,NaN,NaN
6773,2022-10-01,NaN,NaN,NaN,NaN,109.210,NaN,2.4,NaN,NaN,NaN

In [126]:
# 기간 조정
# VKOSPI: 2013.08.06 ~ 2022.11.09
# 월간 변수 다수: ~2022.09
a = a[a['시점'].between('2013-08-06', '2022-09-01')]

In [127]:
pd.set_option('display.min_rows', 100)
a = a.sort_values(by='시점')
a

,시점,Call,InterestDiff,VKOSPI,TradeBalance,CPI,PPI,Unemployment,ManufactProduct,SPREAD,Erlog
4073,2013-08-06,2.500,2.35,0.40,NaN,NaN,NaN,NaN,NaN,NaN,7.015542
4074,2013-08-07,2.480,2.29,2.47,NaN,NaN,NaN,NaN,NaN,2.61,7.018447
4075,2013-08-08,2.490,2.28,-2.50,NaN,NaN,NaN,NaN,NaN,NaN,7.014140
4076,2013-08-09,2.490,2.25,-3.80,NaN,NaN,NaN,NaN,NaN,NaN,7.013160
4077,2013-08-12,2.500,2.29,2.36,NaN,NaN,NaN,NaN,NaN,NaN,7.015685
4078,2013-08-13,2.500,2.37,-3.10,NaN,NaN,NaN,NaN,NaN,NaN,7.019493
4079,2013-08-14,2.500,2.37,-3.30,NaN,NaN,NaN,NaN,NaN,2.61,7.019207
6558,2013-08-15,NaN,2.41,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.019297
4080,2013-08-16,2.500,2.48,3.27,NaN,NaN,NaN,NaN,NaN,NaN,7.014850
4081,2013-08-19,2.500,2.52,1.97,NaN,NaN,NaN,NaN,NaN,NaN,7.019189
4082,2013-08-20,2.500,2.46,7.37,NaN,NaN,NaN,NaN,NaN,NaN,7.021620
4083,2013-08-21,2.500,2.49,3.40,NaN,NaN,NaN,NaN,NaN,2.61,7.018276
4084,2013-08-22,2.500,2.48,1.30,NaN,NaN,NaN,NaN,NaN,NaN,7.021905
4085,2013-08-23,2.500,2.42,-8.00,NaN,NaN,NaN,NaN,NaN,NaN,7.015246
4086,2013-08-26,2.500,2.38,-2.60,NaN,NaN,NaN,NaN,NaN,NaN,7.014455
4087,2013-08-27,2.500,2.34,4.72,NaN,NaN,NaN,NaN,NaN,NaN,7.018205
4088,2013-08-28,2.500,2.38,2.61,NaN,NaN,NaN,NaN,NaN,2.61,7.015937
4089,2013-08-29,2.500,2.36,-0.20,NaN,NaN,NaN,NaN,NaN,NaN,7.014086
4090,2013-08-30,2.510,2.39,0.45,NaN,NaN,NaN,NaN,NaN,NaN,7.011593
6735,2013-09-01,NaN,NaN,NaN,3595081.0,93.419,104.71,2.7,93.525,2.65,NaN
4091,2013-09-02,2.510,NaN,2.48,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4092,2013-09-03,2.510,2.43,-0.60,NaN,NaN,NaN,NaN,NaN,NaN,7.001018
4093,2013-09-04,2.500,2.44,1.50,NaN,NaN,NaN,NaN,NaN,2.65,6.997386
4094,2013-09-05,2.500,2.46,-0.60,NaN,NaN,NaN,NaN,NaN,NaN,7.000152
4095,2013-09-06,2.500,2.48,-1.10,NaN,NaN,NaN,NaN,NaN,NaN,6.995675
4096,2013-09-09,2.500,2.45,2.76,NaN,NaN,NaN,NaN,NaN,NaN,6.990993
4097,2013-09-10,2.510,2.46,-3.10,NaN,NaN,NaN,NaN,NaN,NaN,6.989732
4098,2013-09-11,2.490,2.46,-1.50,NaN,NaN,NaN,NaN,NaN,2.65,6.990035
4099,2013-09-12,2.500,2.47,0.38,NaN,NaN,NaN,NaN,NaN,NaN,6.987278
4100,2013-09-13,2.500,2.45,0.32,NaN,NaN,NaN,NaN,NaN,NaN,6.990146
...,...,...,...,...,...,...,...,...,...,...,...
6284,2022-07-22,2.188,-0.21,-1.50,NaN,NaN,NaN,NaN,NaN,NaN,7.179933
6285,2022-07-25,2.183,-0.19,1.32,NaN,NaN,NaN,NaN,NaN,NaN,7.180275
6286,2022-07-26,2.224,-0.21,-2.90,NaN,NaN,NaN,NaN,NaN,NaN,7.176507
6287,2022-07-27,2.114,-0.18,0.05,NaN,NaN,NaN,NaN,NaN,1.58,7.180176
6288,2022-07-28,2.143,-0.17,-5.30,NaN,NaN,NaN,NaN,NaN,NaN,7.169881
6289,2022-07-29,2.341,-0.22,-3.10,NaN,NaN,NaN,NaN,NaN,NaN,7.169412
6290,2022-08-01,2.238,-0.30,2.42,-9393976.0,108.620,119.98,2.1,112.200,1.85,7.173330
6291,2022-08-02,2.190,-0.31,5.60,NaN,NaN,NaN,NaN,NaN,NaN,7.173874
6292,2022-08-03,2.162,-0.37,-4.10,NaN,NaN,NaN,NaN,NaN,2.85,7.178309
6293,2022-08-04,2.221,-0.35,-4.00,NaN,NaN,NaN,NaN,NaN,NaN,7.177935
6294,2022-08-05,2.242,-0.41,-3.90,NaN,NaN,NaN,NaN,NaN,NaN,7.168749
6295,2022-08-08,2.226,-0.44,0.88,NaN,NaN,NaN,NaN,NaN,NaN,7.174809
6296,2022-08-09,2.243,-0.48,-3.70,NaN,NaN,NaN,NaN,NaN,NaN,7.173575
6297,2022-08-10,2.217,-0.45,4.12,NaN,NaN,NaN,NaN,NaN,2.85,7.178195
6298,2022-08-11,2.215,-0.36,-8.30,NaN,NaN,NaN,NaN,NaN,NaN,7.172210
6299,2022-08-12,2.246,-0.41,-1.80,NaN,NaN,NaN,NaN,NaN,NaN,7.171757
6685,2022-08-15,NaN,-0.41,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.174609
6300,2022-08-16,2.176,-0.43,-0.10,NaN,NaN,NaN,NaN,NaN,NaN,7.176667
6301,2022-08-17,2.175,-0.39,0.58,NaN,NaN,NaN,NaN,NaN,2.85,7.177905
6302,2022-08-18,2.206,-0.34,1.68,NaN,NaN,NaN,NaN,NaN,NaN,7.185342
6303,2022-08-19,2.241,-0.27,-0.20,NaN,NaN,NaN,NaN,NaN,NaN,7.189545
6304,2022-08-22,2.217,-0.29,6.55,NaN,NaN,NaN,NaN,NaN,NaN,7.199977
6305,2022-08-23,2.214,-0.24,5.73,NaN,NaN,NaN,NaN,NaN,NaN,7.199977
6306,2022-08-24,2.258,-0.25,-1.30,NaN,NaN,NaN,NaN,NaN,2.85,7.201954
6307,2022-08-25,2.449,-0.32,-7.30,NaN,NaN,NaN,NaN,NaN,NaN,7.197031
6308,2022-08-26,2.426,-0.33,0.00,NaN,NaN,NaN,NaN,NaN,NaN,7.193814
6309,2022-08-29,2.421,-0.30,15.60,NaN,NaN,NaN,NaN,NaN,NaN,7.207712
6310,2022-08-30,2.428,-0.35,-6.60,NaN,NaN,NaN,NaN,NaN,NaN,7.205167
6311,2022-08-31,2.548,-0.30,-0.90,NaN,NaN,NaN,NaN,NaN,2.85,7.199424
6312,2022-09-01,2.502,-0.25,10.90,-3778132.0,108.930,120.16,2.4,112.000,3.09,7.211070

In [128]:
pd.set_option('display.min_rows', 30)
a = a.fillna(method='bfill')

In [129]:
total = a

In [130]:
total.isna().sum()

시점                 0
Call               0
InterestDiff       0
VKOSPI             0
TradeBalance       0
CPI                0
PPI                0
Unemployment       0
ManufactProduct    0
SPREAD             0
Erlog              0
dtype: int64

In [131]:
total

,시점,Call,InterestDiff,VKOSPI,TradeBalance,CPI,PPI,Unemployment,ManufactProduct,SPREAD,Erlog
4073,2013-08-06,2.500,2.35,0.40,3595081.0,93.419,104.71,2.7,93.525,2.61,7.015542
4074,2013-08-07,2.480,2.29,2.47,3595081.0,93.419,104.71,2.7,93.525,2.61,7.018447
4075,2013-08-08,2.490,2.28,-2.50,3595081.0,93.419,104.71,2.7,93.525,2.61,7.014140
4076,2013-08-09,2.490,2.25,-3.80,3595081.0,93.419,104.71,2.7,93.525,2.61,7.013160
4077,2013-08-12,2.500,2.29,2.36,3595081.0,93.419,104.71,2.7,93.525,2.61,7.015685
4078,2013-08-13,2.500,2.37,-3.10,3595081.0,93.419,104.71,2.7,93.525,2.61,7.019493
4079,2013-08-14,2.500,2.37,-3.30,3595081.0,93.419,104.71,2.7,93.525,2.61,7.019207
6558,2013-08-15,2.500,2.41,3.27,3595081.0,93.419,104.71,2.7,93.525,2.61,7.019297
4080,2013-08-16,2.500,2.48,3.27,3595081.0,93.419,104.71,2.7,93.525,2.61,7.014850
4081,2013-08-19,2.500,2.52,1.97,3595081.0,93.419,104.71,2.7,93.525,2.61,7.019189
4082,2013-08-20,2.500,2.46,7.37,3595081.0,93.419,104.71,2.7,93.525,2.61,7.021620
4083,2013-08-21,2.500,2.49,3.40,3595081.0,93.419,104.71,2.7,93.525,2.61,7.018276
4084,2013-08-22,2.500,2.48,1.30,3595081.0,93.419,104.71,2.7,93.525,2.61,7.021905
4085,2013-08-23,2.500,2.42,-8.00,3595081.0,93.419,104.71,2.7,93.525,2.61,7.015246
4086,2013-08-26,2.500,2.38,-2.60,3595081.0,93.419,104.71,2.7,93.525,2.61,7.014455
...,...,...,...,...,...,...,...,...,...,...,...
6299,2022-08-12,2.246,-0.41,-1.80,-3778132.0,108.930,120.16,2.4,112.000,2.85,7.171757
6685,2022-08-15,2.176,-0.41,-0.10,-3778132.0,108.930,120.16,2.4,112.000,2.85,7.174609
6300,2022-08-16,2.176,-0.43,-0.10,-3778132.0,108.930,120.16,2.4,112.000,2.85,7.176667
6301,2022-08-17,2.175,-0.39,0.58,-3778132.0,108.930,120.16,2.4,112.000,2.85,7.177905
6302,2022-08-18,2.206,-0.34,1.68,-3778132.0,108.930,120.16,2.4,112.000,2.85,7.185342
6303,2022-08-19,2.241,-0.27,-0.20,-3778132.0,108.930,120.16,2.4,112.000,2.85,7.189545
6304,2022-08-22,2.217,-0.29,6.55,-3778132.0,108.930,120.16,2.4,112.000,2.85,7.199977
6305,2022-08-23,2.214,-0.24,5.73,-3778132.0,108.930,120.16,2.4,112.000,2.85,7.199977
6306,2022-08-24,2.258,-0.25,-1.30,-3778132.0,108.930,120.16,2.4,112.000,2.85,7.201954
6307,2022-08-25,2.449,-0.32,-7.30,-3778132.0,108.930,120.16,2.4,112.000,2.85,7.197031
6308,2022-08-26,2.426,-0.33,0.00,-3778132.0,108.930,120.16,2.4,112.000,2.85,7.193814
6309,2022-08-29,2.421,-0.30,15.60,-3778132.0,108.930,120.16,2.4,112.000,2.85,7.207712
6310,2022-08-30,2.428,-0.35,-6.60,-3778132.0,108.930,120.16,2.4,112.000,2.85,7.205167
6311,2022-08-31,2.548,-0.30,-0.90,-3778132.0,108.930,120.16,2.4,112.000,2.85,7.199424
6312,2022-09-01,2.502,-0.25,10.90,-3778132.0,108.930,120.16,2.4,112.000,3.09,7.211070

In [132]:
# 저장
path = 'C:/Users/USER/Desktop/transdata/transdata_temp'
total.to_csv(os.path.join(path, 'Total.csv'), index=False, encoding='cp949')

### 2. VKOSPI 미포함

In [133]:
# 병합
b = pd.merge(call, interestdiff, how='outer')
b = pd.merge(b, tradbal, how='outer')
b = pd.merge(b, cpi, how='outer')
b = pd.merge(b, ppi, how='outer')
b = pd.merge(b, unemploy, how='outer')
b = pd.merge(b, manuprod, how='outer')
b = pd.merge(b, spread, how='outer')
b = pd.merge(b, erlog, how='outer')
b

,시점,Call,InterestDiff,TradeBalance,CPI,PPI,Unemployment,ManufactProduct,SPREAD,Erlog
0,1997-07-07,11.23,0.35,NaN,NaN,NaN,NaN,NaN,NaN,6.790097
1,1997-07-08,11.16,0.35,NaN,NaN,NaN,NaN,NaN,NaN,6.791221
2,1997-07-09,10.95,0.35,NaN,NaN,NaN,NaN,NaN,NaN,6.791221
3,1997-07-10,10.95,0.35,NaN,NaN,NaN,NaN,NaN,NaN,6.792344
4,1997-07-11,11.07,0.34,NaN,NaN,NaN,NaN,NaN,NaN,6.793466
5,1997-07-12,11.07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,1997-07-14,11.20,0.32,NaN,NaN,NaN,NaN,NaN,NaN,6.795146
7,1997-07-15,11.37,0.34,NaN,NaN,NaN,NaN,NaN,NaN,6.795706
8,1997-07-16,11.50,0.33,NaN,NaN,NaN,NaN,NaN,NaN,6.797940
9,1997-07-18,11.43,0.33,NaN,NaN,NaN,NaN,NaN,NaN,6.799056
10,1997-07-19,11.43,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,1997-07-21,11.41,0.33,NaN,NaN,NaN,NaN,NaN,NaN,6.796265
12,1997-07-22,11.38,0.25,NaN,NaN,NaN,NaN,NaN,NaN,6.798498
13,1997-07-23,11.59,0.29,NaN,NaN,NaN,NaN,NaN,NaN,6.798498
14,1997-07-24,11.60,0.29,NaN,NaN,NaN,NaN,NaN,NaN,6.796824
...,...,...,...,...,...,...,...,...,...,...
6759,2020-03-01,NaN,NaN,4363344.0,99.940,102.82,4.2,113.600,-143438.48,NaN
6760,2020-08-01,NaN,NaN,3651302.0,100.190,103.22,3.1,99.700,0.80,NaN
6761,2020-11-01,NaN,NaN,5807120.0,100.090,103.09,3.4,111.800,-999.14,NaN
6762,2021-05-01,NaN,NaN,2814640.0,102.050,108.65,4.0,111.500,0.82,NaN
6763,2021-08-01,NaN,NaN,1584011.0,102.750,110.86,2.6,110.500,1.02,NaN
6764,2022-01-01,NaN,NaN,-4940394.0,104.690,114.40,4.1,115.100,1.58,NaN
6765,2022-05-01,NaN,NaN,-1605818.0,107.560,119.43,3.0,119.900,1.88,NaN
6766,1997-07-01,NaN,NaN,NaN,56.825,69.44,NaN,36.206,NaN,NaN
6767,1998-02-01,NaN,NaN,NaN,61.453,79.72,NaN,32.509,NaN,NaN
6768,1998-03-01,NaN,NaN,NaN,61.349,79.55,NaN,33.999,NaN,NaN
6769,1998-08-01,NaN,NaN,NaN,61.192,77.73,NaN,30.976,NaN,NaN
6770,1998-11-01,NaN,NaN,NaN,61.453,77.69,NaN,37.791,NaN,NaN
6771,1999-05-01,NaN,NaN,NaN,61.712,76.64,NaN,41.044,NaN,NaN
6772,1999-08-01,NaN,NaN,NaN,61.765,76.52,6.2,40.893,NaN,NaN
6773,2022-10-01,NaN,NaN,NaN,109.210,NaN,2.4,NaN,NaN,NaN

In [134]:
# 기간 조정
# 무역수지: 2000.01 ~ 2022.09
b = b[b['시점'].between('2000-01-01', '2022-09-01')]

In [135]:
pd.set_option('display.min_rows', 100)
b = b.sort_values(by='시점')
b

,시점,Call,InterestDiff,TradeBalance,CPI,PPI,Unemployment,ManufactProduct,SPREAD,Erlog
6690,2000-01-01,NaN,NaN,-432198.0,62.456,78.77,5.7,47.748,NaN,NaN
6393,2000-01-03,NaN,0.20,NaN,NaN,NaN,NaN,NaN,NaN,7.028201
646,2000-01-04,4.690,0.19,NaN,NaN,NaN,NaN,NaN,NaN,7.023314
647,2000-01-05,4.710,0.24,NaN,NaN,NaN,NaN,NaN,NaN,7.034388
648,2000-01-06,4.780,0.22,NaN,NaN,NaN,NaN,NaN,NaN,7.044469
649,2000-01-07,4.770,0.21,NaN,NaN,NaN,NaN,NaN,NaN,7.037028
650,2000-01-08,4.780,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
651,2000-01-10,4.720,0.19,NaN,NaN,NaN,NaN,NaN,NaN,7.033065
652,2000-01-11,4.710,0.22,NaN,NaN,NaN,NaN,NaN,NaN,7.044905
653,2000-01-12,4.730,0.23,NaN,NaN,NaN,NaN,NaN,NaN,7.042723
654,2000-01-13,4.710,0.23,NaN,NaN,NaN,NaN,NaN,NaN,7.034828
655,2000-01-14,4.830,0.25,NaN,NaN,NaN,NaN,NaN,NaN,7.025538
656,2000-01-15,4.810,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
657,2000-01-17,4.710,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
658,2000-01-18,4.740,0.28,NaN,NaN,NaN,NaN,NaN,NaN,7.027315
659,2000-01-19,4.740,0.27,NaN,NaN,NaN,NaN,NaN,NaN,7.033506
660,2000-01-20,4.760,0.30,NaN,NaN,NaN,NaN,NaN,NaN,7.026427
661,2000-01-21,4.820,0.31,NaN,NaN,NaN,NaN,NaN,NaN,7.028201
662,2000-01-22,4.790,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
663,2000-01-24,4.770,0.26,NaN,NaN,NaN,NaN,NaN,NaN,7.025094
664,2000-01-25,4.760,0.26,NaN,NaN,NaN,NaN,NaN,NaN,7.027315
665,2000-01-26,4.790,0.24,NaN,NaN,NaN,NaN,NaN,NaN,7.028024
666,2000-01-27,4.780,0.17,NaN,NaN,NaN,NaN,NaN,NaN,7.025538
667,2000-01-28,4.820,0.08,NaN,NaN,NaN,NaN,NaN,NaN,7.021976
668,2000-01-29,4.820,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
669,2000-01-31,4.780,0.07,NaN,NaN,NaN,NaN,NaN,NaN,7.024649
670,2000-02-01,4.760,0.02,652390.0,62.647,78.57,5.7,44.232,NaN,7.027315
671,2000-02-02,4.790,-0.03,NaN,NaN,NaN,NaN,NaN,NaN,7.030857
672,2000-02-03,4.770,-0.07,NaN,NaN,NaN,NaN,NaN,NaN,7.030415
6394,2000-02-04,NaN,-0.10,NaN,NaN,NaN,NaN,NaN,NaN,7.029973
...,...,...,...,...,...,...,...,...,...,...
6284,2022-07-22,2.188,-0.21,NaN,NaN,NaN,NaN,NaN,NaN,7.179933
6285,2022-07-25,2.183,-0.19,NaN,NaN,NaN,NaN,NaN,NaN,7.180275
6286,2022-07-26,2.224,-0.21,NaN,NaN,NaN,NaN,NaN,NaN,7.176507
6287,2022-07-27,2.114,-0.18,NaN,NaN,NaN,NaN,NaN,1.58,7.180176
6288,2022-07-28,2.143,-0.17,NaN,NaN,NaN,NaN,NaN,NaN,7.169881
6289,2022-07-29,2.341,-0.22,NaN,NaN,NaN,NaN,NaN,NaN,7.169412
6290,2022-08-01,2.238,-0.30,-9393976.0,108.620,119.98,2.1,112.200,1.85,7.173330
6291,2022-08-02,2.190,-0.31,NaN,NaN,NaN,NaN,NaN,NaN,7.173874
6292,2022-08-03,2.162,-0.37,NaN,NaN,NaN,NaN,NaN,2.85,7.178309
6293,2022-08-04,2.221,-0.35,NaN,NaN,NaN,NaN,NaN,NaN,7.177935
6294,2022-08-05,2.242,-0.41,NaN,NaN,NaN,NaN,NaN,NaN,7.168749
6295,2022-08-08,2.226,-0.44,NaN,NaN,NaN,NaN,NaN,NaN,7.174809
6296,2022-08-09,2.243,-0.48,NaN,NaN,NaN,NaN,NaN,NaN,7.173575
6297,2022-08-10,2.217,-0.45,NaN,NaN,NaN,NaN,NaN,2.85,7.178195
6298,2022-08-11,2.215,-0.36,NaN,NaN,NaN,NaN,NaN,NaN,7.172210
6299,2022-08-12,2.246,-0.41,NaN,NaN,NaN,NaN,NaN,NaN,7.171757
6685,2022-08-15,NaN,-0.41,NaN,NaN,NaN,NaN,NaN,NaN,7.174609
6300,2022-08-16,2.176,-0.43,NaN,NaN,NaN,NaN,NaN,NaN,7.176667
6301,2022-08-17,2.175,-0.39,NaN,NaN,NaN,NaN,NaN,2.85,7.177905
6302,2022-08-18,2.206,-0.34,NaN,NaN,NaN,NaN,NaN,NaN,7.185342
6303,2022-08-19,2.241,-0.27,NaN,NaN,NaN,NaN,NaN,NaN,7.189545
6304,2022-08-22,2.217,-0.29,NaN,NaN,NaN,NaN,NaN,NaN,7.199977
6305,2022-08-23,2.214,-0.24,NaN,NaN,NaN,NaN,NaN,NaN,7.199977
6306,2022-08-24,2.258,-0.25,NaN,NaN,NaN,NaN,NaN,2.85,7.201954
6307,2022-08-25,2.449,-0.32,NaN,NaN,NaN,NaN,NaN,NaN,7.197031
6308,2022-08-26,2.426,-0.33,NaN,NaN,NaN,NaN,NaN,NaN,7.193814
6309,2022-08-29,2.421,-0.30,NaN,NaN,NaN,NaN,NaN,NaN,7.207712
6310,2022-08-30,2.428,-0.35,NaN,NaN,NaN,NaN,NaN,NaN,7.205167
6311,2022-08-31,2.548,-0.30,NaN,NaN,NaN,NaN,NaN,2.85,7.199424
6312,2022-09-01,2.502,-0.25,-3778132.0,108.930,120.16,2.4,112.000,3.09,7.211070

In [136]:
pd.set_option('display.min_rows', 30)
b = b.fillna(method='bfill')

In [137]:
total_excludeV = b

In [138]:
total_excludeV.isna().sum()

시점                 0
Call               0
InterestDiff       0
TradeBalance       0
CPI                0
PPI                0
Unemployment       0
ManufactProduct    0
SPREAD             0
Erlog              0
dtype: int64

In [140]:
total_excludeV

,시점,Call,InterestDiff,TradeBalance,CPI,PPI,Unemployment,ManufactProduct,SPREAD,Erlog
6690,2000-01-01,4.690,0.20,-432198.0,62.456,78.77,5.7,47.748,-39495.51,7.028201
6393,2000-01-03,4.690,0.20,652390.0,62.647,78.57,5.7,44.232,-39495.51,7.028201
646,2000-01-04,4.690,0.19,652390.0,62.647,78.57,5.7,44.232,-39495.51,7.023314
647,2000-01-05,4.710,0.24,652390.0,62.647,78.57,5.7,44.232,-39495.51,7.034388
648,2000-01-06,4.780,0.22,652390.0,62.647,78.57,5.7,44.232,-39495.51,7.044469
649,2000-01-07,4.770,0.21,652390.0,62.647,78.57,5.7,44.232,-39495.51,7.037028
650,2000-01-08,4.780,0.19,652390.0,62.647,78.57,5.7,44.232,-39495.51,7.033065
651,2000-01-10,4.720,0.19,652390.0,62.647,78.57,5.7,44.232,-39495.51,7.033065
652,2000-01-11,4.710,0.22,652390.0,62.647,78.57,5.7,44.232,-39495.51,7.044905
653,2000-01-12,4.730,0.23,652390.0,62.647,78.57,5.7,44.232,-39495.51,7.042723
654,2000-01-13,4.710,0.23,652390.0,62.647,78.57,5.7,44.232,-39495.51,7.034828
655,2000-01-14,4.830,0.25,652390.0,62.647,78.57,5.7,44.232,-39495.51,7.025538
656,2000-01-15,4.810,0.28,652390.0,62.647,78.57,5.7,44.232,-39495.51,7.027315
657,2000-01-17,4.710,0.28,652390.0,62.647,78.57,5.7,44.232,-39495.51,7.027315
658,2000-01-18,4.740,0.28,652390.0,62.647,78.57,5.7,44.232,-39495.51,7.027315
...,...,...,...,...,...,...,...,...,...,...
6299,2022-08-12,2.246,-0.41,-3778132.0,108.930,120.16,2.4,112.000,2.85,7.171757
6685,2022-08-15,2.176,-0.41,-3778132.0,108.930,120.16,2.4,112.000,2.85,7.174609
6300,2022-08-16,2.176,-0.43,-3778132.0,108.930,120.16,2.4,112.000,2.85,7.176667
6301,2022-08-17,2.175,-0.39,-3778132.0,108.930,120.16,2.4,112.000,2.85,7.177905
6302,2022-08-18,2.206,-0.34,-3778132.0,108.930,120.16,2.4,112.000,2.85,7.185342
6303,2022-08-19,2.241,-0.27,-3778132.0,108.930,120.16,2.4,112.000,2.85,7.189545
6304,2022-08-22,2.217,-0.29,-3778132.0,108.930,120.16,2.4,112.000,2.85,7.199977
6305,2022-08-23,2.214,-0.24,-3778132.0,108.930,120.16,2.4,112.000,2.85,7.199977
6306,2022-08-24,2.258,-0.25,-3778132.0,108.930,120.16,2.4,112.000,2.85,7.201954
6307,2022-08-25,2.449,-0.32,-3778132.0,108.930,120.16,2.4,112.000,2.85,7.197031
6308,2022-08-26,2.426,-0.33,-3778132.0,108.930,120.16,2.4,112.000,2.85,7.193814
6309,2022-08-29,2.421,-0.30,-3778132.0,108.930,120.16,2.4,112.000,2.85,7.207712
6310,2022-08-30,2.428,-0.35,-3778132.0,108.930,120.16,2.4,112.000,2.85,7.205167
6311,2022-08-31,2.548,-0.30,-3778132.0,108.930,120.16,2.4,112.000,2.85,7.199424
6312,2022-09-01,2.502,-0.25,-3778132.0,108.930,120.16,2.4,112.000,3.09,7.211070

In [141]:
# 저장
path = 'C:/Users/USER/Desktop/transdata/transdata_temp'
total.to_csv(os.path.join(path, 'Total_excludeV.csv'), index=False, encoding='cp949')